# Generated by Django 5.1.6 on 2025-06-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
