# Generated by Django 5.1.6 on 2025-06-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_testresult_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
