# Generated by Django 5.1.6 on 2025-06-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_testresult_time_spent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='time_spent',
        ),
        migrations.AlterField(
            model_name='testresult',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Час проходження у секундах'),
        ),
    ]
