# Generated by Django 5.1.6 on 2025-06-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_remove_testresult_time_spent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='duration',
            field=models.PositiveIntegerField(help_text='Час проходження у секундах'),
        ),
    ]
